/// new user Register
POST  http://localhost:5000/register
Content-Type: application/json

{
    "username": "admina",
    "password": "1234",
    "isAdmin" : true
}
###
/// Check Login 
POST http://localhost:5000/login
Content-Type: application/json

{
  "username": "admina",
  "password": "1234"
}
###
/// Post Contact
POST http://localhost:5000/contact
Content-Type: application/json

{
    "firstName":"Bb4554",
    "lastName":"Brown",
    "streetNumber":"Berliner Straße 22",
    "zip":"10715",
    "city":"Berlin",
    "state":"Berlin",
    "country":"Germany",
    "isPublic":true,
    "lat":"",
    "long":"",
    "owerID":"admina"
}
###
//Show All Contacts
GET http://localhost:5000/contact
Content-Type: application/json

###
///Show contact with id
GET http://localhost:5000/contact/60e3cfdfcf6aa71b3c05aae2
Content-Type: application/json

###
///Change Contact with id
PUT http://localhost:5000/contact/60e3cfdfcf6aa71b3c05aae2
Content-Type: application/json

{
    "firstName":"Hung",
    "lastName":"Tran",
    "streetNumber":"Berliner Straße 22",
    "zip":"10715",
    "city":"Berlin",
    "state":"Berlin",
    "country":"Germany",
    "isPublic":false,
    "lat":"52.520008",
    "long":"13.404954",
    "owerID":"normalo"
}

###
///Delete Contact with id
DELETE  http://localhost:5000/contact/60e3eaa7b41b0304f4e69979
Content-Type: application/json




